version: "3.7"

services:
  concur_download:
    container_name: concur_download
    restart: always
    image: concur_download
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/concur_download

