version: "3.7"

services:
  simple_crud:
    container_name: simple_crud
    restart: always
    image: simple_crud

    build: .
    ports:
      - "8082:8080"
    volumes:
      - ./:/simple_crud
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./:/simple_crud/docker-entrypoint-initdb.d


